spin_manifest_version = 2

[application]
name = "new"
version = "0.1.0"
authors = ["Andrew Steurer <andrew.steurer@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "new"

[component.new]
source = "main.wasm"
# files = ["message.txt"]
allowed_outbound_hosts = ["http://localhost:3000"]
[component.new.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/crypto/..."
component = "crypto"

[component.crypto]
source = {url = "https://github.com/asteurer/test/raw/master/main.wasm", digest = "sha256:43ed9e2d1e5e73801e7ce76dba45d93f7b88774b49e2703e820d011927f947f7"}
allowed_outbound_hosts = []